Description: |
  YAML Configuration file with dummy authentication parameters, demonstrates format of what the authentication parameters should look like for your tenant
  This example includes the following design choices for illustrative purposes:
  - Use of Pascal case convention for variable names
ProductNames:
  - aad
  - teams
M365Environment: commercial
Organization: abcdef.example.com
AppID: 0123456789abcdef01234566789abcde
CertificateThumbprint: fedcba9876543210fedcba9876543210fedcba98
